model:
  model_name: "WFCG"

data_input: 
  # dataset_name: IndianPines
  # dataset_name: CowCube
  # dataset_name: CowCube_DE
  dataset_name: CowCube_ML
  # dataset_name: PigletCube
  # dataset_name: PigletCube_DE
  # dataset_name: HumenCube
  # dataset_name: HumenCube_DE
  # dataset_name = 'Loukia'
  # dataset_name = 'Dioni'
  # dataset_name = 'hanchuan'
  # dataset_name = "pavia"
  # dataset_name = "Salinas"
  # classes: 16
  classes: 2

data_split:
  samples_type: ratio
  # number
  # ratio
  train_num: 10
  val_num: 0
  train_ratio: 0.01
  val_ratio: 0.01
  superpixel_scale: 2000

network_config:
  max_epoch: 300
  learning_rate: 0.001
  weight_decay: 0.001
  lb_smooth: 0.01

result_output:
  # path_weight: E:\HSI_Classification\ZZ_WFCG\weights\
  # path_result: E:\HSI_Classification\ZZ_WFCG\results\

  path_weight: HSI_Classification/ZZ_WFCG/weights/ # here
  path_result: HSI_Classification/ZZ_WFCG/results/




