model:
  model_name: "WFCG"

data_input: 
  # dataset_name: porcine1_696x520x31
  dataset_name: "porcine2_696x520x31"
  # dataset_name: porcine3_696x520x31
  # dataset_name: porcine4_696x520x31

  # traind_on: "AA"
  # traind_on: "AB"
  # traind_on: "AC"
  # traind_on: "BA"
  # traind_on: "BB"
  # traind_on: "BC"
  # traind_on: "CA"
  # traind_on: "CB"
  # traind_on: "CC"




  # classes: 16
  classes: 2


data_split:
  # samples_type: ratio
  samples_type: fixed
  # number
  # ratio
  split_size: 0.01
  train_num: 10
  val_num: 0
  train_ratio: 0.01
  val_ratio: 0.01
  superpixel_scale: 2000

network_config:
  max_epoch: 200
  learning_rate: 0.001
  weight_decay: 0.001
  lb_smooth: 0.01

result_output:
  path_weight: HSI_Classification/ZZ_WFCG/weights/ # not used
  path_result: ../../HSI DL Results/